### ISSUE TITLE
[Question]: Can an alert be shown without dismissing the keyboard?

### ISSUE THREAD

**Issue by bitwit** [sberrevoets/SDCAlertView#119]
I'm not sure that it's a bug so much as a feature/quirk of the library, but when editing a textfield, if an alert is presented, it dismisses the keyboard, then brings it back after I dismiss the alert.

Is there a way to prevent this?

Thanks

**Comment by sberrevoets** [comment]
This is not possible. The reason is that the user is in a completely different context when an alert is presented. Suddenly they are no longer editing text, but dealing with the options of an alert. It would be weird to have the keyboard up because, the keyboard either doesn't do anything, or it types text in the dimmed area which is dimmed because it's irrelevant. The focus is on the alert, not on anything else.

**Comment by bitwit** [comment]
I agree, you shouldn't be able to interact with the keyboard, but I'd assumed it would be part of a dimmed layer below rather than still in the foreground. Similar to the effect in Clear when you set a reminder time, the calendar date picker takes over the foreground without the keyboard dismissing behind.

I think what I might be looking for is more of a custom modal.

Many thanks

**Comment by sberrevoets** [comment]
Ah that's an interesting approach. Since keyboards are separate windows, my guess is that Clear creates another window to lay over the keyboard and dim it that way. That works if the view controller stays the same (because then there would be no change in first responder), but in this case the view controller changes and there is no easy way to keep the current keyboard up.

Sorry, but I don't think this is worth the effort.

**Comment by bitwit** [comment]
Thanks, yes, let's keep SDCAlerts doing one thing really well. Cheers
