### ISSUE TITLE
VisualStyle textColorForAction ignored when tintColor set.

### ISSUE THREAD

**Issue by lasvegasgamer** [sberrevoets/SDCAlertView#137]
The documentation reads

>SDCAlertController is a normal view controller, so applying a tintColor to its view will color the buttons and any subviews you add to the contentView. If you are looking for more customizations, create a type that conforms to VisualStyle and use visualStyle on the AlertController instance.

This implies a type conforming to VisualStyle which implements textColorForAction would be used.

```Swift
class IgnoredVisualStyle : VisualStyle {
    
public func textColor(forAction action: AlertAction?) -> UIColor {
        return UIColor.whiteColor()
    }
}
```

This is not the case.

```Swift
    func presentSDCAlertController() {
            self.view.window?.tintColor = UIColor.purpleColor()
            let alert = AlertController(title: "title", "message": message, preferredStyle: .Alert)
            alert.visualStyle = IgnoredVisualStyle()
            alert.present()
    }
```

Expected Result: White Color
Actual Result: Purple Color

=============================
We can see why in ActionCell.swift
```Swift
//Logging added
    func setAction(action: AlertAction, withVisualStyle visualStyle: VisualStyle) {
		...
        self.titleLabel.textColor = visualStyle.textColor(forAction: action)
        print("setActionTextColor")
    }

    override func tintColorDidChange() {
        super.tintColorDidChange()
        print("tintColorDidChange")
        self.titleLabel.textColor = self.tintColor
    }
```

```
Console Output when AlertController presented
-----------------
setActionTextColor
tintColorDidChange
```

UIKit will call tintColorDidChange when alerts are presented, so this code (and by the extension) the documentation are inaccurate as of iOS 9.2

**Comment by lasvegasgamer** [comment]
Happy to submit a PR with a fix, but wanted to post the issue first.

In our current client implementation, we have removed tintColorDidChange from ActionCell, but I imagine that wouldn't be appropriate upstream.

However, since the type doesn't keep a reference to its visual style around, there's no way to add any additional logic in tintColorDidChange unless I'm missing something?

**Comment by sberrevoets** [comment]
This was more or less intended as such. The `tintColor` is supposed to have priority over the visual style because it will *always* have a visual style (even if just the default one), so setting a `tintColor` wouldn't have an effect if it didn't have priority over the visual style.

However, that does mess up in cases where you want a tint color but you don't want that tint color to apply to the actions. In most cases it doesn't make much sense to do that as the buttons are the only elements that get tinted. However, if you add a custom subview that you do want tinted, but you don't want the buttons to be tinted, that could lead to the problem you're running into.

**Comment by lasvegasgamer** [comment]
Thanks for the quick response!

> This was more or less intended as such. The tintColor is supposed to have priority over the visual style because it will always have a visual style (even if just the default one), so setting a tintColor wouldn't have an effect if it didn't have priority over the visual style.

Makes sense technically, and philosophically too… understand the need for any project to stick to some opinionated defaults. 

But, speaking of always having something…in light of the unique way UIKit goes hunting for a tintColor (from the docs)

> The first nondefault tint color value in the view’s hierarchy, ascending from and starting with the view itself. If the system cannot find a nondefault color in the hierarchy, this property’s value is a system-defined color instead.

Put another way, there’s always the possibility of a tintColor out there somewhere in the hierarchy,  regardless of what someone using SDCAlertView tries to set. Therefore, while your logic above makes sense, doesn’t it also obviate any reason to even have a textColorForAction method in VisualStyle?

**Comment by sberrevoets** [comment]
> Put another way, there’s always the possibility of a tintColor out there somewhere in the hierarchy, regardless of what someone using SDCAlertView tries to set. Therefore, while your logic above makes sense, doesn’t it also obviate any reason to even have a textColorForAction method in VisualStyle?

`tintColor` would apply to all buttons (and other tintable UI elements in the hierarchy), whereas `textColorForAction` could be tailored to individual actions/buttons. For example, you may want to use the tint color of your app for 2 buttons, but a custom red color for a destructive button. Without `textColorForAction` that wouldn't be possible.

**Comment by sberrevoets** [comment]
One way to solve this is by making `textColorForAction()` return an optional `UIColor`. That way, if a color is returned it can have precedence over the `tintColor`, and if it's nil the `tintColor` will be used.

That does cause some difficulty regarding `tintColorDidChange()` and knowing whether to actually update the button or not. Feel free to submit a PR for that if you have the time. Otherwise I'll get to it at some point, though that may take a bit.

**Comment by sberrevoets** [comment]
Closing in favor of the PR.
