### ISSUE TITLE
SDCAlertview for Objective C

### ISSUE THREAD

**Issue by shalini90** [sberrevoets/SDCAlertView#180]
We are updating SDCAlertview from 2.5.4 to 7.0 .Our project is completely in objective  c.

Many weird errors and "file not found" errors occurs during this update. Any proper documentation how to use this in objective c project would be helpful. Please help on this.

I could not see any SDCAlertViewDelegate in swift version. Does this still supports objective c.

**Comment by sberrevoets** [comment]
The library definitely still supports Objective-C, but upgrading from 2.5.4 to 7.0 might require some changes as the public API has changed a bit. I'd check out the generated header file in Xcode to see what's new and what has changed. Most of the API that was there before is still there but may have been renamed slightly. `SDCAlertViewDelegate` was removed in 2.0, so that shouldn't cause too much trouble.

**Comment by shalini90** [comment]
Thanks @sberrevoets  for the info.

If you have any sample project for integrating swift version of  SDCAlertView for Objective C project, It would be very helpful for others who are using it.

**Comment by sberrevoets** [comment]
There is no sample project, but other than the `SDC` prefix, there shouldn't be major differences between the Objective-C and Swift versions of the library.

If you `@import SDCAlertView;` in Objective-C and type `SDCAlertController` you can command click on that symbol and it will take you to the Objective-C header file that exposes all the public classes and properties.

Closing this now, but feel free to open another issue if you run into problems!
