### ISSUE TITLE
Sample code is not working

### ISSUE THREAD

**Issue by timautin** [sberrevoets/SDCAlertView#182]
The sample code provided on the project page is not working as is for an iOS 8 / Swift 3 project (seems to be iOS 9 / Swift 2.3). Would be nice to update it in order to be able to test the lib as fast as possible.

Thanks

**Comment by sberrevoets** [comment]
If you're talking about the code in the README: that code is for iOS 9 targets since it uses the anchor layout APIs that iOS 9 introduced. The alert itself is usable on iOS 8 and before, but to keep the sample code short I used iOS 9+ code there.

For a more in-depth example of how to build something check out the sample project or use `pod try SDCAlertView`.

**Comment by timautin** [comment]
Thanks for the fast answer!

Yes I'm referring to the README. Thanks for pointing the sample project, but still, I think that it would be better to have a snippet that can run on iOS 8 in the README ;) .

But now it doesn't matter for me, as I decided to go with my own implementation ^^ .

**Comment by sberrevoets** [comment]
Sounds good, I'll close this issue then!
