### ISSUE TITLE
ActionSheet title nil, but contentView is visible

### ISSUE THREAD

**Issue by dimacheverda** [sberrevoets/SDCAlertView#185]
I'm creating `AlertController` like this:

```
let actionSheet = AlertController(title: nil, message: nil, preferredStyle: .actionSheet)
actionSheet.add(AlertAction(title: "Cancel", style: .destructive))
actionSheet.add(AlertAction(title: "Yes", style: .normal))
actionSheet.present()
```

[Screenshot](http://i.imgur.com/b8FLphO.png)

But getting strange empty space above button where title and message labels should go, since I don't need them I passed `nil` into `AlertController` init method. Tried to solve issue using different `AlertVisualStyle` options such as `contentPadding`, `margins`, custom `contentView` with 0 height, but all of this seems not working.

Maybe I'm not using it right, anyway `.alert` style is working fine, only this one strange thing. Can provide more details if needed.

Using latest `master` branch version.
`pod 'SDCAlertView', :git => 'https://github.com/sberrevoets/SDCAlertView.git', :branch => 'master'`
Xcode 8.0 (8A218a)
iOS 10.0
macOS 10.11

**Comment by sberrevoets** [comment]
Thanks for a detailed report! You're right, there is some empty space because that view is hardcoded to 59 points. I'm not entirely sure why it was, but I _believe_ that in iOS 9 that space was always there (for the same reason, a hardcoded height for the area with the labels) as well. Would you mind double-checking that?

In any case, on iOS 10 that space isn't there anymore that needs to be fixed. Feel free to take a stab at it if you want!

**Comment by sberrevoets** [comment]
Thanks for submitting a PR, let's continue there.
