### ISSUE TITLE
Constraints broken after accessing AlertView height

### ISSUE THREAD

**Issue by antipex** [sberrevoets/SDCAlertView#206]
I have a custom view in an AlertController, and I'm trying to set the height based on the height of the AlertView. If I access the AlertView `frame.size.height` property the constraints on the entire view end up broken, leaving the content view improperly sized and the actions missing.

This line consistently reproduces the issue:
```
let height = alert.view.frame.size.height
```

That's all it takes – simply accessing the property.

**Comment by sberrevoets** [comment]
Yeah that makes sense. As soon as the alert's view is loaded, most changes are set in stone because that "event" is used to determine the entire layout. If you haven't added buttons yet before accessing the view, those won't be added at all.

That said, accessing the alert's view is not something you should do. `AlertController` is a view controller, and view controllers have a `view` property, but actually using it is unsupported.

**Comment by antipex** [comment]
> If you haven't added buttons yet before accessing the view, those won't be added at all.

Ah I see, that makes sense.
