### ISSUE TITLE
keyboard not dimissing

### ISSUE THREAD

**Issue by Nathan187** [sberrevoets/SDCAlertView#221]
not sure what i'm doing wrong...

if made an alert with two textfields (username, password) and two buttons (cancel, proceed)....if i enter data for both fields...when i tap proceed....the alert dismisses but the keyboard is still present.  i've tried all kinds of things to get that keyboard to dismiss.  not sure what i'm doing wrong. 

(it dismisses in the simulator but not on the device.   any suggestions would be nice

**Comment by sberrevoets** [comment]
This sounds very similar to https://github.com/sberrevoets/SDCAlertView/issues/217.

Are you using iOS 11?

**Comment by Nathan187** [comment]
thank you for the fast reply.  i'm using swift 3.  i'm thinking if i switch to swift 4, it'll break everything.  i'm not using iOS 11

**Comment by sberrevoets** [comment]
Ok, in that case can you create a sample project that reproduces this?

**Comment by nboyd-sportdx** [comment]
i've attached a simple/sample project.   it's targeted at 10.2 (the current i pad I have is 10.2)

i think it has something to do with showing the alert within an @ibaction?   

thanks in advance for any help
[Archive.zip](https://github.com/sberrevoets/SDCAlertView/files/1150457/Archive.zip)

**Comment by sberrevoets** [comment]
I took a look, and the first time I ran it I saw the problem. I tried the same in the Example project, it didn't reproduce, and then when I built the original again I didn't see it there anymore either.

I suspect something in UIKit is going wrong, but right now I'm not sure what since I don't have good repro steps.

FWIW, I doubt it has anything to do with showing the alert from an `IBAction`, but who knows ¯\\\_(ツ)_/¯

**Comment by Nathan187** [comment]
that's so weird...not sure why it would start working for no reason.   did you try running it on the device....did it behave the same?

**Comment by sberrevoets** [comment]
Yeah this is all on an iPad mini. I got it to reproduce reliably and investigated a bit, and it seems that the private `_firstResponder` is set to `nil` when the keyboard is still showing, which is very weird and most likely a problem in UIKit. It stopped reproducing again so I'm pretty sure there's some weird state issue happening in UIKit.

I made sure there are no memory leaks (text fields that are not showing but could still have first responder status or something), and I tried a bunch of things like calling `resignFirstResponder()` and `endEditing(true)` manually, but it doesn't seem to help. I've also not been able to reproduce this on the `swift-4` branch, so I'm hoping that this is a problem in UIKit that's fixed with iOS 11. Otherwise I'm afraid I'm not sure what to do about this 😕

**Comment by Nathan187** [comment]
hey man, thank you for your quick and detailed response.  it was baffling me and i too was trying to do the resignfirstresponder / self.view.endediting , etc.   i created a custom popover to do the work.  i'm glad it wasn't something i was doing wrong.   

thanks for your help
