### ISSUE TITLE
Can dismiss AlertView by tapping outside but with no option.

### ISSUE THREAD

**Issue by Xy2501** [sberrevoets/SDCAlertView#250]
Under the newest versiont (8.0.1), the alertView, by default, can be dismissed by tapping outside of the alertView. However there no option to choose not to. Later on I saw that method "self.addChromeTapHandlerIfNecessary()" is added under "configureAlertView". Could you please fix it by adding an option that one can choose not to dismiss the alertView when tapping outside of it? Thanks

**Comment by sberrevoets** [comment]
This is a bug in the library that has been fixed on master but has not yet made it to a new release. I'm a bit swamped at the moment but will create a new release soon. In the meantime, you can use master or fork the library to get this fix in.

For reference, the bug was fixed here: https://github.com/sberrevoets/SDCAlertView/pull/242

**Comment by Xy2501** [comment]
Alright，Thanks.

Sent from my iPhone

On Nov 28, 2017, at 11:40, Scott Berrevoets <notifications@github.com<mailto:notifications@github.com>> wrote:


This is a bug in the library that has been fixed on master but has not yet made it to a new release. I'm a bit swamped at the moment but will create a new release soon. In the meantime, you can use master or fork the library to get this fix in.

For reference, the bug was fixed here: #242<https://github.com/sberrevoets/SDCAlertView/pull/242>
