### ISSUE TITLE
Update alert view size

### ISSUE THREAD

**Issue by piotrros** [sberrevoets/SDCAlertView#264]
Inside alert content, I have a UIStackView with some views inside. Now, I have a button, which can hide and show some stuff. The thing is alert size isn't changing. Instead, it scrolls. I tried stuff like setNeedsLayout and updateConstraints, but it doesn't seem to be working. When everything is shown initially it doesn't shrink alert size and vice versa.

**Comment by sberrevoets** [comment]
I'm not sure exactly what you're doing, but it sounds like it makes sense. The alert is pretty much immutable, except for a few things such as labels, after presenting.

In your case, you could try calling `invalidateIntrinsicContentSize()` on the alert and see if that works.

**Comment by piotrros** [comment]
AlertController doesn't have invalidateIntrinsicContentSize() method. Instead I tried calling:

        alert.contentView.invalidateIntrinsicContentSize()
        alert.updateViewConstraints()

But it doesn't seem to be working.

**Comment by sberrevoets** [comment]
Sorry I meant on `alert.view`.

**Comment by piotrros** [comment]
I tried everything:

```
        alert.view.invalidateIntrinsicContentSize()
        alert.view.setNeedsLayout()
        alert.view.updateConstraints()
        alert.view.layoutIfNeeded()
        
        alert.contentView.invalidateIntrinsicContentSize()
        alert.contentView.setNeedsLayout()
        alert.contentView.updateConstraints()
        alert.contentView.layoutIfNeeded()
        
        calendarStackView.invalidateIntrinsicContentSize()
        calendarStackView.setNeedsLayout()
        calendarStackView.updateConstraints()
        calendarStackView.layoutIfNeeded()
        
        alert.updateViewConstraints()
```

**Comment by sberrevoets** [comment]
If you can upload a sample project that reproduces this I can take a look.

**Comment by piotrros** [comment]
Sure, here it is:
[AlertIssue.zip](https://github.com/sberrevoets/SDCAlertView/files/1795996/AlertIssue.zip)

**Comment by sberrevoets** [comment]
It looks like the issue here is that your calendar view and the alert's content are leaving it up to each other to be sized. The stack view can expand fine (the labels will just stretch) and the alert would be accommodating that. If you specify an explicit height for the view that's added to the content view I think it'll work.

**Comment by piotrros** [comment]
How? To the main stack view or the one, which contain calendar? Anyway, I tried adding height constraint to both and switch height, I got some conflicts, but alert size hasn't changed.

**Comment by sberrevoets** [comment]
Stack views make this difficult because they're designed to be flexible and the alert is as well, which means there's layout ambiguity. In my very quick testing I gave the calendar stack view a height and updated that in `updateCalendarView()` which seemed to work.

(You'll also notice when you run the app there's a runtime error for ambiguous scrollable content, which also goes away if you set a height to the stack view)

**Comment by piotrros** [comment]
Can you upload changed project, please? As I said, I tried this, but it didn't work :(
