### ISSUE TITLE
shouldDismissHandler if set, does not send action handler for other buttons

### ISSUE THREAD

**Issue by hanumanXplor** [sberrevoets/SDCAlertView#268]
_self.alert.actionTappedHandler = { [weak self] action in
            if self?.shouldDismissHandler?(action) != false {
                self?.dismiss(animated: true) {
                    action.handler?(action)
                }
            }
// should have else, send the action.handler?(action) without dismissing
        }_

**Comment by podmat** [comment]
Any update on this? It's a critical bug, I have a TextField inside alert dialog and I can't do validation, because action's handler is not called when `shouldDismissHandler ` returns `false`

**Comment by sberrevoets** [comment]
This was done so by design. Reason is that UIAlertController only calls back to this closure when an alert is dismissed, and I wanted that to remain consistent.

Changing this poses 2 problems:

1. There's no great way to detect whether an action that was tapped actually caused the alert to dismiss or not, without resorting to hacks like checking if the alert is still on screen.
2. It breaks any current users of the library without any notice whatsoever, which I really want to avoid.

Definitely open to solving this in other ways though!

**Comment by podmat** [comment]
Thank you for fast reply, oh sorry I didn't know that it's by design (I'm new to this lib). 
Right now I moved action handling to `shouldDismissHandler`, but is it a recommended way?
If you don't want to do breaking changes, maybe cleaner option would be to add second handler for `AlertAction` (used for dismissal prevention), just an idea.

**Comment by sberrevoets** [comment]
I'm not sure there is a recommended way, I think it's better to say that functionality is currently not supported.

I think adding an additional parameter (`didDismiss`) to the existing closure might be a better solution then.

**Comment by karishmapujara** [comment]
So any solution?

**Comment by sberrevoets** [comment]
This is currently not possible, no.

**Comment by karishmapujara** [comment]
So we can't run some code when user pressed any other button except Cancel !!!

**Comment by hanumanXplor** [comment]
I solved it by creating a fork and updating following
`            if self?.shouldDismissHandler?(action) != false {
                self?.dismiss(animated: true) {
                    action.handler?(action)
                }
            } else {
                action.handler?(action)
            }
`

**Comment by sberrevoets** [comment]
Feel free to reopen if there are other suggestions to solve this taking into consideration my comments from before!
