### ISSUE TITLE
Privacy Manifest

### ISSUE THREAD

**Issue by mobru** [sberrevoets/SDCAlertView#333]
Hi there,

As of May 1st 2024, Apple requires third-party SDKs to add a Privacy Manifest file.
https://developer.apple.com/support/third-party-SDK-requirements/
https://developer.apple.com/documentation/bundleresources/privacy_manifest_files

Are there plans to include a Privacy Manifest?

**Comment by sberrevoets** [comment]
See https://github.com/sberrevoets/SDCAlertView/issues/332

I don't think this library requires a privacy manifest but if you think differently please let me know!

**Comment by mobru** [comment]
Honestly, I’m not entirely sure myself. Apple is vague here - they do say that 3rd party SDKs are required to do so.
Does the SDCAlertView use the UserDefaults, or any other “required reason API” (see https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api)? If so , then yes, you need one. If not… idk??
I could make one for you via a pull request, but probably not before April (I’m on vacation until them) if you’d prefer?

**Comment by sberrevoets** [comment]
Right, it's my understanding that since the library doesn't use any of those APIs no privacy manifest is required. We've been getting warnings from Apple for libraries that do require one but haven't added it yet, so I think that means SDCAlertView is safe. Let's wait and see for a bit and if it becomes clear it does need one we can add one at that time.
