### ISSUE TITLE
Background color

### ISSUE THREAD

**Issue by marcinjackowski** [sberrevoets/SDCAlertView#66]
Hi, i have a big question for you ! It is possible to change background color in your library ? I'am looking for it all day but i couldn't change it. Please help me.. I want to do this on both ios 7 and 8. Please help me to do sth like this : ( background color looks like half tansparent ) 

![zrzut ekranu 2014-11-17 o 14 32 30](https://cloud.githubusercontent.com/assets/9006718/5070801/e88694ce-6e6a-11e4-9f19-70e048bd5560.png)

**Comment by phaitour** [comment]
One quick observation:  it seems the SDCAlertController background color is a few shades darker than the iOS 8 alert view background color.  If you look at the default alert views, they are first presented in a light light gray and then quickly flash to the slightly translucent background that blurs the views behind the alert.  Is there a chance the default background color can be updated for ios 7/8?

**Comment by sberrevoets** [comment]
Unfortunately not. It's certainly not the same, but Apple internally uses a private class for alerts that uses a different visual effect than `UIVisualEffectView`. I haven't been able to figure out what exactly is going on there, so I had to settle for using `UIVisualEffectView`.

**Comment by phaitour** [comment]
So it seems you *can* update the `backgroundColor` of the appearance of `UIVisualEffectView`.  You lose most of the blur/translucency effect, but you can tweak the tint of the background.

**Comment by sberrevoets** [comment]
Very interesting. Were you able to adjust its background to make it look more like the system alert?

**Comment by phaitour** [comment]
You get closer to the system alert popup.  It's not a perfect match, but because the background is a few shades lighter it's harder to tell the difference.  But like I mentioned earlier, setting a `backgroundColor` to the appearance appears to affect the blur effect... so pick one or the other hehe.

**Comment by sberrevoets** [comment]
Hmm, so that probably means that on light backgrounds (where the blur isn't as obvious) the one with a background color looks better, and on brighter background where the blur has a clear effect, the current one. Not sure what to pick then...

**Comment by sberrevoets** [comment]
@phaitour One of my coworkers today mentioned that if you set a `tintColor` on the `UIVisualEffectView` (instead of the `backgroundColor`) you don't actually lose the blur effect. I probably won't have time to try this for a while, but I figured I'd let you know in case you want to try it.

**Comment by phaitour** [comment]
@sberrevoets Thanks!  I just tried it, but it didn't seem to work for me.  The tint color affected the button text color, but not the background color.  Although... I only tried setting the tint color to the `UIVisualEffectView`'s appearance and not the tint color of the actual view object.  Not sure if that would make a difference...

**Comment by phaitour** [comment]
@sberrevoets Interestingly, I used this to solve another problem I was experiencing.  

I noticed that if you have multiple alerts shown on top of one another the non-foreground alerts get grayed out (in particular the button color).  When these alerts come to the foreground, the button color goes back to the default blue and completely disregards the color set in the visual style.

So to solve this problem, I just set the button color to the `UIVisualEffectView`'s tint color.

**Comment by sberrevoets** [comment]
Hmm, yeah that would be a problem. I'd appreciate a PR on that!

**Comment by phaitour** [comment]
Hmm, so changing the tint color has an adverse side effect:  it forces the action button color to ignore any overriding values set in an attributed string.  Because of this, I'm not submitting a PR for this... maybe we'll find another fix for the backgrounded alerts' buttons changing color down the road.

Additionally, I noticed that `SDCAlertCollectionViewCell`'s `updateWithAction:...` function has a small bug.  Because the font and textColor are set after an attributed string is set, it effectively overrides any font/text color settings in the attributed string itself.  I'll attach a PR for this.
