### ISSUE TITLE
Why no animated parameter on present and dismiss?

### ISSUE THREAD

**Issue by gbrhaz** [sberrevoets/SDCAlertView#84]
When presenting and dismissing the alert controller the subsequent calls have animated forced to YES; was there any point in not having this parameter in the parent function as well?

**Comment by gbrhaz** [comment]
OK, so after further investigation it seems altering the methods so they don't dismiss animatedly actually breaks them. I guess this is why it was done? Any way to get this fixed?

**Comment by sberrevoets** [comment]
This was a corner I cut rather than a deliberate decision. I figured most alerts would be presented with animation, so I hardcoded it to `YES` for now. Adding an `animated` parameter to `presentWithCompletion:` shouldn't be a big deal.

The same should apply to dismissing without animation, so I'm not entirely sure what it is that's breaking. Can you give me some sample code/screenshot/animated GIF to show what is going on?

**Comment by sberrevoets** [comment]
I was just trying to implement this functionality, but unfortunately it requires changing the name of `presentWithCompletion:` to `presentAnimated:completionHandler`. According to the rules of semantic versioning, that would require updating the major version as well. It seems a little overkill to increment the major version just for this extra argument.

I'll be sure to implement this whenever I increment the major version, which will likely be around the time iOS 9 is introduced.

**Comment by sberrevoets** [comment]
I just released version 3.0 that has support for this. Thanks for your patience!
